resolver: lts-8.3
packages:
  - location: '.'
  - location:
      git: https://github.com/ejconlon/analyze.git
      commit: b45a84de8b2bb4233caa6ce4a4bbe30ce36f68f3
extra-deps: []

flags: {}

extra-package-dbs: []
